module.exports.config = {
    name: "Fanta",
    version: "1.0.0",
    hasPermission: 0,
    credits: "August Quinn",
    description: "Generate a random character with attributes, description, and a plot.",
    commandCategory: "Fun",
    usages: "/Fanta",
    cooldowns: 5
};

const getRandomElement = (array) => {
    return array[Math.floor(Math.random() * array.length)];
};

const getRandomVowel = () => {
    const vowels = "aeiou";
    return getRandomElement(vowels);
};

const getRandomLastNameLength = () => {
    return Math.floor(Math.random() * 7) + 3; 
};

const capitalizeFirstLetter = (word) => {
    return word.charAt(0).toUpperCase() + word.slice(1).toLowerCase();
};

module.exports.run = async function ({ api, event, args }) {
    const firstNameAlphabets = "bcdfghjklmnpqrstvwxyz";
    const lastNameAlphabets = "abcdefghijklmnopqrstuvwxyz";
    const appearanceAdjectives = [
  "Tall",
  "Short",
  "Muscular",
  "Lean",
  "Elegant",
  "Graceful",
  "Rugged",
  "Lithe",
  "Stocky",
  "Svelte",
  "Slender",
  "Statuesque",
  "Compact",
  "Brawny",
  "Delicate",
  "Stout",
  "Athletic",
  "Willowy",
  "Chiseled",
  "Robust",
  "Petite",
  "Voluptuous",
  "Angular",
  "Colossal",
  "Lanky",
  "Powerful",
  "Curvaceous",
  "Sinewy",
  "Mighty",
  "Fragile",
  "Hulking",
  "Dainty",
  "Solid",
  "Lissome",
  "Bulky",
  "Nimble",
  "Endowed",
  "Slouching",
  "Agile",
  "Pudgy",
  "Austere",
  "Toned",
  "Plump",
  "Rakish",
  "Vigorous",
  "Gawky",
  "Fierce",
  "Gentle",
  "Steely",
  "Delightful",
  "Compact",
  "Stalwart",
  "Willful",
  "Angular",
  "Fleshy",
  "Resplendent",
  "Robust",
  "Supple",
  "Wiry",
  "Lithe",
  "Solid",
  "Vibrant",
  "Invincible",
  "Exquisite",
  "Dynamic",
  "Slender",
  "Buoyant",
  "Majestic",
  "Trim",
  "Burly",
  "Animated",
  "Pliable",
  "Muscular",
  "Glamorous",
  "Lanky",
  "Brawny",
  "Ravishing",
  "Buxom",
  "Sturdy",
  "Imposing",
  "Curvy",
  "Charming",
  "Dapper",
  "Plump",
  "Valiant",
  "Gallant",
  "Elegant",
  "Lean",
  "Nimble",
  "Mighty",
  "Dainty",
  "Stout",
  "Toned",
  "Lithe",
  "Majestic",
  "Fierce",
  "Supple",
  "Stalwart",
  "Gentle",
  "Rugged",
  "Invincible",
  "Delicate",
  "Dynamic",
  "Brawny"
];
    const ages = ["Young", "Middle-aged", "Elderly"];
    const genders = ["Male", "Female", "Non-binary"];
    const worlds = [
  "Fantasy",
  "Sci-Fi",
  "Historical",
  "Modern",
  "Steampunk",
  "Cyberpunk",
  "Post-Apocalyptic",
  "Mythological",
  "Space Opera",
  "Dystopian",
  "Utopian",
  "Alternate History",
  "Time Travel",
  "Magical Realism",
  "Gothic",
  "Surreal",
  "Superhero",
  "Epic",
  "Whimsical",
  "Fairy Tale",
  "Hard Science Fiction",
  "Alien Invasion",
  "Parallel Universe",
  "Cosmic Horror",
  "Biopunk",
  "Sword and Sorcery",
  "Gaslamp Fantasy",
  "Ancient Civilization",
  "Mythpunk",
  "Urban Fantasy",
  "Military Science Fiction",
  "Solarpunk",
  "Mythopoeia",
  "Mythical Creature",
  "Robotic",
  "Nautical",
  "Apocalyptic",
  "High Tech",
  "Low Tech",
  "Desert World",
  "Jungle World",
  "Oceanic",
  "Underground",
  "Skyborne",
  "Ice Planet",
  "Forest World",
  "Floating Islands",
  "Virtual Reality",
  "Dimensional Rift",
  "Wasteland",
  "Mystical",
  "Magitech",
  "Biomechanical",
  "Pirate",
  "Infinite",
  "Dreamscape",
  "Alien Civilization",
  "Artificial Intelligence",
  "Time Paradox",
  "Alchemy",
  "Cryptid",
  "Apocalyptic Earth",
  "Space Western",
  "Galactic Empire",
  "Interdimensional",
  "Subterranean",
  "Mecha",
  "Nano",
  "Clash of Realities",
  "Hidden",
  "Lost World",
  "Mythical Realm",
  "Otherworldly",
  "Alternate Reality",
  "Stellar",
  "Enchanted",
  "Technomagic",
  "Conspiracy",
  "Futuristic",
  "Mythical Kingdom",
  "Vast Universe",
  "Doomsday",
  "Mind-Bending",
  "Enigmatic"
];
    const races = [
  "Elf",
  "Dwarf",
  "Orc",
  "Alien",
  "Elunian",
  "Dwark",
  "Aetherian",
  "Sylph",
  "Gorgonite",
  "Celestial",
  "Chthonian",
  "Vulpine",
  "Aquarian",
  "Lyrian",
  "Terradon",
  "Aviorian",
  "Nephilim",
  "Ignarite",
  "Selkie",
  "Dracolite",
  "Minotauran",
  "Eurydite",
  "Pixiemorph",
  "Golem",
  "Merithian",
  "Arcanite",
  "Wyrm",
  "Enigmari",
  "Luminal",
  "Zephyrkin",
  "Kraken",
  "Centaurian",
  "Telkarus",
  "Phoenician",
  "Ursid",
  "Infernali",
  "Faelorian",
  "Glacian",
  "Caelumite",
  "Sphinxian",
  "Atlantari",
  "Onyxfolk",
  "Nixie",
  "Titanborn",
  "Auroran",
  "Geistwalker",
  "Shadowdancer",
  "Arachnarian",
  "Lycorian",
  "Magmian",
  "Pandoran",
  "Tidelord",
  "Dryadin",
  "Emberite",
  "Aereling",
  "Crystalite",
  "Hallowed",
  "Umbra",
  "Skycloud",
  "Moltenkin",
  "Luminaught",
  "Infernavian",
  "Eclipsid",
  "Solarian",
  "Frostweaver",
  "Zephyrian",
  "Thunderkind",
  "Siren",
  "Quicksilver",
  "Celestid",
  "Silvershaper",
  "Draconarch",
  "Illusiphin",
  "Clockwork",
  "Starforged",
  "Mossfolk",
  "Nebulite",
  "Terralith",
  "Verdantian",
  "Ashenfolk",
  "Frostborn",
  "Flamewrought",
  "Echoharmon",
  "Skywarden",
  "Auroraclad",
  "Quillborne",
  "Veilstriker",
  "Lumisire",
  "Icemara",
  "Thunderbark",
  "Embermaw",
  "Cogwhirr",
  "Starwhisper",
  "Gloomwrought",
  "Tidecaster",
  "Stormshaper",
  "Loomweaver",
  "Dawnspire",
  "Frosthaven",
  "Wildroot",
  "Radiant",
  "Shadowbound",
  "Quartzinite",
  "Sparkweald"
];
    const plotTwists = [
  "A hidden prophecy foretells their destiny.",
  "They possess a mysterious artifact with great power.",
  "Their past is shrouded in mystery and danger.",
  "An unexpected alliance changes the course of their journey.",
  "Their loyalty is put to the ultimate test.",
  "A trusted mentor is revealed to be a traitor.",
  "The antagonist is a long-lost relative.",
  "The main goal they've been pursuing turns out to be a deception.",
  "A parallel universe version of the protagonist enters the story.",
  "A minor character from the beginning becomes the key to their success.",
  "The antagonist's motivations are driven by a tragic loss.",
  "The mentor's guidance is actually a series of manipulated events.",
  "A powerful organization that seemed benign is unveiled as malevolent.",
  "A character's recurring nightmare becomes a vital clue.",
  "The prophecy was misinterpreted, leading to unexpected consequences.",
  "A sudden betrayal comes from the least likely ally.",
  "The mentor sacrifices themselves for the protagonist.",
  "A hidden letter unveils a secret identity.",
  "An old childhood friend resurfaces with hidden intentions.",
  "The main quest was a test set up by their own people.",
  "The antagonist's true goal is to save the world, not destroy it.",
  "The protagonist gains a new ability that comes with a terrible price.",
  "A forbidden love between characters on opposing sides complicates matters.",
  "A curse thought to be a metaphor becomes frighteningly real.",
  "The story's setting is a simulation controlled by advanced beings.",
  "A map they've been following leads to an entirely different treasure.",
  "The antagonist's memories have been manipulated, fueling their actions.",
  "A character's seemingly mundane skill becomes the linchpin of the plot.",
  "The solution to their quest lies in deciphering an ancient language.",
  "A time loop reveals that they've been repeating the same events.",
  "A character's deepest fear is exploited by the antagonist.",
  "A hidden society with its own rules emerges within the main world.",
  "The characters discover they are living in a post-apocalyptic reality.",
  "The main quest turns out to be a distraction from a looming disaster.",
  "The mentor's motives are to avenge a past betrayal.",
  "A character's imaginary friend from childhood reappears as a guide.",
  "The prophecy is revealed to be a manipulation by a higher power.",
  "The antagonist's evil plan is a result of mistaken identity.",
  "A character's forgotten past holds the key to saving the world.",
  "The group finds out they are all connected by a shared past event.",
  "The antagonist is a manifestation of the protagonist's subconscious fears.",
  "A hidden code within a song leads them to an unexpected location.",
  "The characters realize they are characters in a storyteller's book.",
  "A cursed object thought to be destroyed returns to haunt them.",
  "A character gains the ability to see glimpses of the future.",
  "The antagonist's true form is a misunderstood and tragic creature.",
  "The mentor is an immortal who has been guiding heroes for centuries.",
  "The protagonist's greatest strength becomes their greatest weakness.",
  "The characters enter a virtual world that affects the outcome of reality.",
  "The antagonist's ultimate weapon is powered by the protagonist's emotions.",
  "A long-lost sibling becomes a central figure in the conflict.",
  "The mentor's rival offers assistance, but their intentions are unclear.",
  "A character's reflection starts acting independently, revealing secrets.",
  "The group is betrayed by one of their own from an alternate timeline.",
  "A mysterious illness begins to affect the abilities of magic users.",
  "The antagonist's tragic backstory is revealed through hidden journals.",
  "The characters must navigate a series of dream worlds to save reality.",
  "A character's greatest fear is the key to unlocking a sealed power.",
  "The protagonist's memories have been tampered with, changing their identity.",
  "The antagonist's power source is linked to an endangered magical creature.",
  "A forbidden ritual is their only hope, but it comes at a great cost.",
  "The characters discover their world is a tiny fragment of a shattered realm.",
  "The antagonist is an older version of the protagonist driven mad by power.",
  "A legendary hero thought to be dead returns as a vengeful spirit.",
  "The characters find out they are part of an elaborate social experiment.",
  "A character's art or music holds the secret to defeating the antagonist.",
  "The antagonist's cruelty is a result of being possessed by a malevolent spirit.",
  "A mysterious clock counts down to an event that could reshape reality.",
  "The protagonist is chosen not to save the world, but to end it.",
  "The characters realize they are all different incarnations of the same soul.",
  "The antagonist's kingdom is a facade, covering a realm of suffering.",
  "A character gains the ability to enter paintings and explore their worlds.",
  "The mentor's guidance was actually a series of carefully crafted lies.",
  "The group discovers a hidden city with technology far beyond their time.",
  "The antagonist's power increases with each lie they tell.",
  "A character's reflection shows a different person, hinting at a split reality.",
  "The characters learn that their world is a forgotten creation of their own minds.",
  "An ancient curse causes the characters to swap bodies, testing their bonds.",
  "The antagonist's ultimate goal is to merge all dimensions into one.",
  "A character's recurring vision leads them to a powerful, dormant artifact.",
  "The mentor's wisdom is drawn from stealing ideas from other dimensions.",
  "The group must navigate a series of traps set up by a previous hero.",
  "The antagonist's enforcer is revealed to be a tragic hero from the past.",
  "A character gains the ability to hear others' thoughts, uncovering secrets.",
  "The characters must gather fragments of a shattered reality to save their world.",
  "The antagonist's power is drawn from the emotions of those who fear them.",
  "A character's imaginary world starts to leak into reality, causing chaos.",
  "The mentor's true form is a mythical creature in disguise.",
  "The group discovers that time travel was responsible for their quest's initiation.",
  "The antagonist's actions are driven by a desperate need to save their family.",
  "A character's shadow gains sentience, craving to replace its owner.",
  "The characters find out that the antagonist is an alternate version of themselves.",
  "The mentor's long-lost love returns as an antagonist seeking revenge.",
  "A character's forgotten diary contains the answers they seek.",
  "The antagonist's power is linked to a cursed object they cannot let go of.",
  "The group learns that their reality is just one layer of a multiverse.",
  "A character gains the ability to manipulate dreams, affecting reality.",
  "The protagonist discovers they are the embodiment of an ancient prophecy.",
  "The antagonist's plan is a ruse to identify the world's true heroes.",
  "A character's true identity is hidden behind a magically constructed persona.",
  "The group finds a way to communicate with beings from other dimensions.",
  "The antagonist's strength grows with every act of kindness they witness.",
  "A character's emotions become tied to the elements, affecting the environment.",
  "The characters must relive the same day until they can make the right choices.",
  "The antagonist's immortality is a result of a deal with dark entities.",
  "A character gains the ability to rewind time but risks erasing their existence.",
  "The group learns that their memories are fabricated and their lives are a lie.",
  "The antagonist's true identity is known only to those they spare.",
  "A character's weapon is the only thing that can destroy the antagonist's source of power.",
  "The protagonist's quest is a loop designed to refine their abilities for a greater purpose."
];
     const skillAttributesVariations = [
  "with a unique set of skills and attributes",
  "with exceptional abilities that defy the norm",
  "possessing remarkable talents honed through years of practice",
  "bearing an innate mastery of diverse skills",
  "carrying an impressive arsenal of abilities that astonish all who witness",
  "whose skills seem almost supernatural in nature",
  "with a rare blend of talents that complement each other perfectly",
  "possessing skills that have been passed down through generations",
  "with a natural affinity for harnessing ancient magic",
  "whose abilities have been augmented by advanced technology",
  "with skills that draw power from their emotions",
  "whose talents are the result of a scientific experiment gone awry",
  "with abilities tied to the phases of the moon",
  "bearing skills that have been hidden for centuries by a secret society",
  "with a connection to the spirit realm that enhances their abilities",
  "whose skills evolve and adapt in the heat of battle",
  "possessing a dormant power that awakens in times of crisis",
  "with skills rumored to be a gift from the gods",
  "carrying a cursed skill that comes with a heavy price",
  "with abilities that are amplified in the presence of certain elements",
  "possessing skills that blur the line between reality and illusion",
  "with a skill that allows them to manipulate time itself",
  "bearing a mark that grants them access to ancient and forbidden abilities",
  "with a skillset curated by a mysterious benefactor",
  "possessing skills stolen from fallen enemies",
  "with abilities tied to a sentient and ancient weapon",
  "carrying a skill that grants them control over the minds of others",
  "with a unique skill born from their connection to a rare creature",
  "possessing skills that can reshape the fabric of reality",
  "with abilities tied to their unwavering determination and willpower",
  "bearing a skillset that changes with the cycles of the seasons",
  "with a skill granted by a powerful cosmic entity",
  "possessing skills that tap into the energy of ley lines",
  "with abilities awakened by a near-death experience",
  "carrying a skill that allows them to communicate with animals",
  "with a skillset fueled by their intense and vivid dreams",
  "possessing skills granted by a mysterious and ancient tome",
  "with abilities that draw strength from the bonds they forge with others",
  "bearing a mark that grants them control over the elements",
  "with a skill that allows them to see glimpses of the future",
  "possessing skills linked to their connection with the natural world",
  "with abilities tied to their affinity for music and rhythm",
  "carrying a skill that grants them mastery over illusions",
  "with a skillset honed through battles fought in other realms",
  "possessing skills that have been enhanced by a near-death experience",
  "with abilities that are awakened by extreme emotions",
  "bearing a mark that grants them access to hidden knowledge",
  "with a skill that allows them to manipulate dreams",
  "possessing skills tied to their exploration of ancient ruins",
  "with abilities that are tied to their unique genetic heritage",
  "carrying a skill that grants them control over technology",
  "with a skillset that mirrors the constellations above",
  "possessing skills granted by an enigmatic and otherworldly entity",
  "with abilities that are tied to their mastery of a long-forgotten art",
  "bearing a mark that grants them control over life and death",
  "with a skill that allows them to navigate alternate dimensions",
  "possessing skills tied to their connection with the oceans and seas",
  "with abilities awakened through their exploration of the mind",
  "carrying a skill that grants them the power to manipulate emotions",
  "with a skillset that evolves as they learn and adapt",
  "possessing skills that tap into the energy of the stars",
  "with abilities granted by a mysterious celestial event",
  "bearing a mark that grants them control over dreams",
  "with a skill that allows them to manipulate the fabric of space",
  "possessing skills linked to their encounters with ancient spirits",
  "with abilities that are tied to their unwavering compassion",
  "carrying a skill that grants them mastery over the weather",
  "with a skillset that changes in response to the phases of the moon",
  "possessing skills granted by a sentient and ancient tree",
  "with abilities that are awakened by their exposure to ancient artifacts",
  "bearing a mark that grants them control over the flow of time",
  "with a skill that allows them to communicate with the dead",
  "possessing skills that tap into the energy of the earth itself",
  "with abilities that are tied to their affinity for the stars",
  "carrying a skill that grants them the power to manipulate fate",
  "with a skillset that draws strength from their connections with others",
  "possessing skills granted by a mysterious and powerful being",
  "with abilities that are awakened through their exploration of emotions",
  "bearing a mark that grants them control over the threads of destiny",
  "with a skill that allows them to navigate the boundaries of reality",
  "possessing skills tied to their connection with ancient spirits",
  "with abilities that are awakened by their understanding of the universe",
  "carrying a skill that grants them mastery over the very essence of life",
  "with a skillset that is a reflection of their innermost desires",
  "possessing skills that tap into the energy of the cosmos",
  "with abilities granted by a celestial alignment",
  "bearing a mark that grants them control over the balance of nature",
  "with a skill that allows them to communicate with celestial beings",
  "possessing skills that are a testament to their journey through time",
  "with abilities that are tied to their bond with mythical creatures",
  "carrying a skill that grants them the power to reshape reality itself"
];
  const randomFirstNameLength = Math.floor(Math.random() * 6) + 4;
    let randomFirstName = "";
    for (let i = 0; i < randomFirstNameLength; i++) {
        if (i % 2 === 0) {
            randomFirstName += getRandomElement(firstNameAlphabets);
        } else {
            randomFirstName += getRandomVowel();
        }
    }

    const randomLastNameLength = getRandomLastNameLength();
    let randomLastName = "";
    for (let i = 0; i < randomLastNameLength; i++) {
        randomLastName += getRandomElement(lastNameAlphabets);
    }

    const randomAppearance = getRandomElement(appearanceAdjectives);
    const randomAge = getRandomElement(ages);
    const randomGender = getRandomElement(genders);
    const randomWorld = getRandomElement(worlds);
    const randomRace = getRandomElement(races);
    const randomPlotTwist = getRandomElement(plotTwists);
    const randomSkillAttribute = getRandomElement(skillAttributesVariations);

    const formattedFirstName = capitalizeFirstLetter(randomFirstName);
    const formattedLastName = capitalizeFirstLetter(randomLastName);

    const articleForRace = ["A", "E", "I", "O", "U"].includes(randomRace.charAt(0).toUpperCase()) ? "an" : "a";

    const characterDescription = `𝗖𝗛𝗔𝗥𝗔𝗖𝗧𝗘𝗥 𝗣𝗥𝗢𝗙𝗜𝗟𝗘\nFull Name: ${formattedFirstName} ${formattedLastName}\nPhysical Appearance: ${randomAppearance}\nAge: ${randomAge}\nGender: ${randomGender}\nFrom the World of: ${randomWorld}\nRace: ${articleForRace} ${randomRace}\n\n𝗗𝗘𝗦𝗖𝗥𝗜𝗣𝗧𝗜𝗢𝗡\n${formattedFirstName} ${formattedLastName} is ${articleForRace} ${randomRace.toLowerCase()} ${randomSkillAttribute}.\n\n𝗣𝗟𝗢𝗧 𝗧𝗪𝗜𝗦𝗧\n${randomPlotTwist}`;

    api.sendMessage(characterDescription, event.threadID, event.messageID);
};